### ISSUE TITLE
Hungarian phone number mask might be incorrect...

### ISSUE THREAD

**Issue by Balage666** [ChristoPy/countries-phone-masks#17]
The pattern of the hungarian mask doesn't match with examples on this wikipedia article: [Telephone_numbers_in_Hungary](https://en.wikipedia.org/wiki/Telephone_numbers_in_Hungary). 
According to this, it either should be (##)###-#### or ## ### ####.

**Comment by ChristoPy** [comment]
Thanks for the issue!

Will submit a fix

**Comment by ChristoPy** [comment]
Hey! Just fixed in 1.1.1 version fb0687af01cc42e1007e0e1061a6d1c8acc3e677
