### ISSUE TITLE
Incorrect countries.json after update

### ISSUE THREAD

**Issue by Lukianov** [ChristoPy/countries-phone-masks#3]
After update there is typo in countries.json in line 98 ("mask" field )

`{
    "name": "Ascension Island",
    "code": "+247",
    "iso": "AC",
    "flag": "https://cdn.kcak11.com/CountryFlags/countries/sh.svg",
    "mask": "####"[a-z]*.svg
  },`

**Comment by ChristoPy** [comment]
Thanks for the issue.

Pull request #4 was merged with the fix.
